/* Additional record code for BouncingBall generated by the OpenModelica Compiler OpenModelica 1.27.0. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "BouncingBall_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

