import esbuild from "esbuild";
import process from "process";
// Node's own list, rather than the `builtin-modules` package. The list is already here,
// and that package is one the plugin directory asks plugins to replace.
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Modelica Studio — Obsidian plugin
if you want to view the source, visit the plugin's GitHub repository
*/
`;

const prod = process.argv[2] === "production";

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  // Obsidian runs plugins in an Electron renderer with Node integration, so
  // node builtins stay as runtime require() calls rather than being bundled.
  platform: "node",
  // Obsidian only ever downloads manifest.json, main.js and styles.css.
  // Everything must therefore collapse into this one CommonJS file.
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    // The `node:`-prefixed spellings are distinct specifiers to esbuild.
    ...builtinModules.map((m) => `node:${m}`),
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
});

if (prod) {
  await ctx.rebuild();
  process.exit(0);
} else {
  await ctx.watch();
}
